FROM mcr.microsoft.com/mssql/server:2019-latest

ENV SA_PASSWORD=BikeServiceProject
ENV ACCEPT_EULA=Y

COPY ./BikeServiceAPI/Migrations/ ./Migrations/

FROM mcr.microsoft.com/dotnet/runtime:7.0 AS runtime

RUN dotnet ef database update --project ./BikeServiceAPI/BikeServiceAPI.csproj --context BikeServiceDbContext --verbose
