name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Restore NuGet packages
        run: nuget restore BikeServiceAPI.sln

      - name: Build and run NUnit tests
        run: |
          dotnet test BikeServiceAPI.sln --logger "trx;LogFileName=test_results.trx"

  build:
    needs: test
    if: ${{ needs.test.result == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set image tag
        id: set_image_tag
        run: echo "::set-output name=tag::$(date +'%Y%m%d')"

      - name: Build docker image
        run: docker build -t krisztanzero/bike-service-project:bike-service-api-${{ steps.set_image_tag.outputs.tag }} ./BikeServiceAPI

      - name: Push docker image
        run: docker push krisztanzero/bike-service-project:bike-service-api-${{ steps.set_image_tag.outputs.tag }}