name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run NUnit tests
        uses: ./.github/workflows/run-test.yml

      - name: Dockerize if tests pass
        uses: ./.github/workflows/dockerize.yml
