name: Test and Docker

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development
  workflow_dispatch:

jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Restore NuGet packages
        run: nuget restore BikeServiceAPI.sln

      - name: Run lint test
        run: dotnet build --configuration Release /p:StyleCopEnabled=true

  nunit-test:
    needs: lint-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Restore NuGet packages
        run: nuget restore BikeServiceAPI.sln

      - name: Build and run NUnit tests
        run: |
          dotnet test BikeServiceAPI.sln --logger "trx;LogFileName=test_results.trx"

  build_and_run:
    needs: nunit-test
    if: ${{ needs.nunit-test.result == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build docker image
        run: docker build -t krisztanzero/bike-service-project:bike-service-api:latest ./BikeServiceAPI

      - name: Run Docker container
        run: docker run -d -p 8080:80 krisztanzero/bike-service-project:bike-service-api:latest

  push_to_dockerhub:
    needs: build_and_run
    if: ${{ needs.build_and_run.result == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push docker image
        run: docker push krisztanzero/bike-service-project:bike-service-api:latest